### ISSUE TITLE
how to handle routes?

### ISSUE THREAD

**Issue by TaylorPzreal** [preciousDev/angularJS-webpack-ocLazyLoad#1]
how did you do to handle the whole application routes? is all declared at main.js? it's so bigger.how to split by service module?
thx very much.

**Comment by theiliad** [comment]
application routes, what do you mean?

If you're talking about the angular ui-router routes, there are only 2, & they're all here:
https://github.com/preciousDev/angularMaterial-webpack2-ocLazyLoad/blob/master/app-content/main/main.js

Does that answer your question?

**Comment by theiliad** [comment]
You can always separate routes into different module routes like Angular2-4 does it.

Just move them into different files and **require** them in main.js

**Comment by theiliad** [comment]
Just made a commit with those changes added in.

Just add a file with the extension of **.routes.js** in the each module folder, and put in the routes in the file. It will automatically get imported in
