### ISSUE TITLE
same project but with typescript

### ISSUE THREAD

**Issue by AGuyCoding** [preciousDev/angularJS-webpack-ocLazyLoad#2]
i would love to see the same project but with typescript files, somehow i am not able to get it working.
I added a "tsconfig.json", added "ts-loader" for webpack, edited the webpack for the ".ts" extension and added "ts-loader".

I would be glad for help!

p.s.: thanks for this repository

**Comment by theiliad** [comment]
@benjaminadrom Sorry missed this issue. Did you get it to work?

**Comment by AGuyCoding** [comment]
no problem, yes sort of, thanks.
